### ISSUE TITLE
Melpa PR

### ISSUE THREAD

**Issue by pnf** [clojure-emacs/squiggly-clojure#11]
With the @lunaryorn refactoring, this is now three separate Flycheck checkers, so I don't think there should be any further objection.

**Comment by purcell** [comment]
Now that everything is `flycheck-clojure-*` internally - which is great! - we can (and should) rename the file to `flycheck-clojure.el` before packaging it.

**Comment by pnf** [comment]
Done.  I shall retain the charmingly whimsical naming on the Clojure side.

**Comment by purcell** [comment]
:+1:  Great -- I tweaked the headers in the file to keep package.el happy, and I've added a MELPA recipe, so a package should show up at http://melpa.org/#/flycheck-clojure soon!

**Comment by arrdem** [comment]
:+1: thanks guys!
