### ISSUE TITLE
"Error from syntax checker clojure-cider-eastwood: Done with no errors"

### ISSUE THREAD

**Issue by zilti** [clojure-emacs/squiggly-clojure#13]
I freshly added squiggly-clojure to my installation and hooked into a REPL, and this was the first message I got. It seems to completely break squiggly-clojure.

**Comment by pnf** [comment]
Hi Daniel -
Did you load the ```C-c l`` the Clojure buffer?  I see the (admittedly misleading) message you report when I forget to do that.

**Comment by zilti** [comment]
Yes, I've loaded it, and that solved it - I guess I was irritated by this showing up in the first place.

**Comment by pnf** [comment]
Well, we can't have irritated users...  Seriously, I don't think this should be happening, so I reopened the issue.

**Comment by pnf** [comment]
And, with the last git and clojars put, it should be fixed.
There were two redundant causes for the problem.  First, we weren't specifying a namespace to run Clojure commands in, so Cider tries to infer one from the source and then 'ns' to it, despite the fact that it doesn't exist yet.   Fixing that, by specifying "user" explicitly, we would have a close relative of the problem when we passed the non-existent namespace to the various checkers, so now we check for existence first.  

@bbatsov I noticed that, while `nrep-request:eval` supports not setting a namespace at all, by passing in `nil`, `cider-eval` always tries to infer one unless it's set explicitly by the caller.   That would only be a problem if there were a good reason for not setting any namespace, and I can't currently think of one, but maybe you can.

**Comment by zilti** [comment]
Ok. The only "problem" now is that this namespace isn't always the same, e.g. the `boot` build tool uses `boot.user` and not just `user` as Leiningen does. But maybe I'm also misunderstanding you and this doesn't matter.

**Comment by pnf** [comment]
Ok, I think you identified a reason for not specifying any namespace.  I had an uncommitted patch for this that I've now committed.
