### ISSUE TITLE
New install results in FileNotFound exception

### ISSUE THREAD

**Issue by markcwhitfield** [clojure-emacs/squiggly-clojure#19]
This project looks great! However, after setting up according to the README, I'm currently getting the following error any time a .clj buffer is modified:

```
Error from syntax checker clojure-cider-eastwood: Form #[257 \300\301"\207 [format (do (require 'squiggly-clojure.core) (squiggly-clojure.core/check-ew '%s))] 4 

(fn NS)] of checker clojure-cider-eastwood failed: class java.io.FileNotFoundException
```

`*nrepl-messages*` shows the following:
```
(--->
  op  "eval"
  session  "9b0456a0-9899-481f-a345-12bdbe5f8c9b"
  code  "(do (require 'squiggly-clojure.core) (squiggly-clojure.core/check-ew 'working-title.core.routes.address-book-routes))"
  id  "36"
)
(<-
  ex  "class java.io.FileNotFoundException"
  id  "36"
  root-ex  "class java.io.FileNotFoundException"
  session  "9b0456a0-9899-481f-a345-12bdbe5f8c9b"
  status  ("eval-error")
)
(<-
  err  "FileNotFoundException Could not locate squiggly_clojure/core__init.class or squiggly_clojure/core.clj on classpath:   clojure.lang.RT.load (RT.java:443)\n"
  id  "36"
  session  "9b0456a0-9899-481f-a345-12bdbe5f8c9b"
)
(<-
  id  "36"
  session  "9b0456a0-9899-481f-a345-12bdbe5f8c9b"
  status  ("done")
)
```

This is with the proper plugins in `profiles.clj`:
```
{:user {:plugins [[cider/cider-nrepl "0.9.0-SNAPSHOT"]
                  [refactor-nrepl "0.2.2"]
                  [acyclic/squiggly-clojure "0.1.2-SNAPSHOT" :exclusions [org.clojure/core.cache]]]}}
```

I'm new to both clojure and emacs, so I'm not sure if it's as simple as this, but the clojars entry for squiggly-clojure is currently [pointing at the old, now-empty repo](https://clojars.org/acyclic/squiggly-clojure).

**Comment by pnf** [comment]
Hi - thanks for trying out the module!
I believe the problem is that `[acyclic/squiggly-clojure "0.1.2-SNAPSHOT"]` needs to be in the `:dependencies:` of the project's `project.clj` rather than in the `:plugins` section of the global  `profiles.clj`. 

---

**Comment by tanzoniteblack** [comment]
You can also place it in the `: dependencies` section of the global
profiles.clj instead :plugins of the global or in a local project.clj
