### ISSUE TITLE
next-error-function is unchanged

### ISSUE THREAD

**Issue by expez** [clojure-emacs/squiggly-clojure#20]
The keys `M-n` and `M-p` are bound to `next-error` and `previous-error` respectively.  It's common to override the `next-error-function` to make these navigational commands work properly.  Right now these are bound by cider to `cider-jump-to-compilation-error` which means flycheck errors can't be navigated.

Alternatively we could put this in the `README`:

```elisp
(add-hook 'cider-mode-hook 
  (lambda () (setq next-error-function #'flycheck-next-error-function)))
```

**Comment by pnf** [comment]
Advice added to README:
If you're used to `flycheck` but not used to `cider`, you may want
~~~.el
(add-hook 'cider-mode-hook 
  (lambda () (setq next-error-function #'flycheck-next-error-function)))
~~~
to override the binding to ````cider-jump-to-compilation-error`.
