### ISSUE TITLE
Getting (wrong-type-argument stringp nil) on simple project

### ISSUE THREAD

**Issue by OlegTheCat** [clojure-emacs/squiggly-clojure#30]
Hi.

I'm getting the following error on simple project (almost no code there):

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  signal(wrong-type-argument (stringp nil))
  #[257 "\300 \210\301@A\"\207" [flycheck-report-failed-syntax-check signal] 4 "\n\n(fn ERR)"]((wrong-type-argument stringp nil))
  funcall(#[257 "\300 \210\301@A\"\207" [flycheck-report-failed-syntax-check signal] 4 "\n\n(fn ERR)"] (wrong-type-argument stringp nil))
  flycheck-buffer()
  #[0 "\300 \207" [flycheck-buffer] 1 "\n\n(fn)"]()
  funcall(#[0 "\300 \207" [flycheck-buffer] 1 "\n\n(fn)"])
  flycheck-buffer-automatically(idle-change)
  flycheck-handle-idle-change()
  apply(flycheck-handle-idle-change nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 22120 40256 428447 nil flycheck-handle-idle-change nil nil 509000])
```

My config is as follows:

* CIDER 0.10.0
* lein profiles:
```
{:user {:plugins [[lein-localrepo "0.5.2"]
                  [cider/cider-nrepl "0.10.0"]
                  [refactor-nrepl "1.1.0"]]
        :dependencies [[acyclic/squiggly-clojure "0.1.4"]
                       [org.clojure/tools.nrepl "0.2.12"]]}}
```

* clojure 1.7.0

I suppose that there's some conflicts in configuration and I'd be glad if someone pointed me where to look for solution.

Thanks in advance.

**Comment by arichiardi** [comment]
Yep I confirm, I had to disable it as well

**Comment by expez** [comment]
Refactor-nrepl 1.1.0 doesn't work with clojure 1.7 due to the breaking changes made to the reader.  Upgrade to 2.0.0-snapshot for now along with the version available on melpa (not melpa stable) for the emacs portion.

**Comment by arichiardi** [comment]
Ah ok good to know,  I will pull snapshot then

**Comment by OlegTheCat** [comment]
Unfortunately, usage of refactor-nrepl-2.0.0-SNAPSHOT didn't help :(

**Comment by codeitagile** [comment]
Same issue for me, with same versions as @OlegTheCat

**Comment by akahl-lshift** [comment]
I found the problem. `cider-flycheck-eval` is invoked with `nil` for the `connection` argument. I'll prepare a fix in a fork.

**Comment by OlegTheCat** [comment]
@akahl-lshift after this fix squiggly seems to be working. Thanks a lot.

**Comment by benedekfazekas** [comment]
again, quite unrelated but clj-refactor/refactor-nrepl 2.0.0 is out for a few weeks now too ;)
