### ISSUE TITLE
some way to specify eastwood config

### ISSUE THREAD

**Issue by expez** [clojure-emacs/squiggly-clojure#33]
Hi 

Eastwood has support for a configuration file, to set up exceptions etc.  It would would be awesome if we had some way to configure squiggly clojure to use that file.

**Comment by pnf** [comment]
I think the most general thing to do would be to add `:eastwood-options` to the other squiggly configuration options, so you can override anything you want, e.g.
```
  :profiles {:dev {:env {:squiggly {:checkers [:eastwood :typed]
                                    :eastwood-exclude-linters [:unlimited-use]
                                    :eastwood-options { :builtin-config-files ["myconfigfile.clj"]
                                                                     :debug (:time :progress)
                                                                   })}}}

```
So you can specify a `:builtin-config-files` vector within that.  (Far be it from me to come up with a better name.)  I'll leave `:eastwood-exclude-linters` alone, though it's now redundant.

**Comment by pnf** [comment]
I've pushed `0.1.5`.

**Comment by expez** [comment]
Perfect! :+1:
