### ISSUE TITLE
eastwood config file path in readme is wrong

### ISSUE THREAD

**Issue by expez** [clojure-emacs/squiggly-clojure#36]
The keyword to specify own config files is `:config-files`.  The `:builtin-config-files` key is used to override the vector of config files already included in eastwood.  See the eastwood readme for further details.

**Comment by pnf** [comment]
Fixed.  Though the point here is that absolutely anything you put in `:eastwood-options` will be merged in and passed to `eastwood/lint`, without notice or comment by squiggly-colure.

**Comment by expez** [comment]
Still a minor type there `:config:files `

> Though the point here is that absolutely anything you put in `:eastwood-options` will be merged in and passed to `eastwood/lint`, without notice or comment by squiggly-colure.

Yeah, I got that after reading the code to figure out why my settings were being ignored.
