### ISSUE TITLE
Eastwood version need upgrade

### ISSUE THREAD

**Issue by bobotu** [clojure-emacs/squiggly-clojure#44]
As eastwood README said:

> - Clojure 1.8.0 - Use Eastwood 0.2.2 or later. There are known problems using Eastwood 0.2.1 and earlier with Clojure 1.8.0.
> - Clojure 1.5.1, 1.6.0, or 1.7.0 - Many versions of Eastwood have been tested with these, up through Eastwood 0.2.3.

Can we upgrade to eastwood 0.2.3 or 0.2.2 to fix errors on Clojure 1.8.0

**Comment by pnf** [comment]
Updated to eastwood 0.2.3, kibit 0.1.3 and core.typed 0.3.26.  A new version of squiggly has been deployed to clojars, so you'll need to change the dependency to `[acyclic/squiggly-clojure "0.1.7"]`.  It will probably take a day for the elisp to propagate to melpa; in the mean time, if you use `cider-jack-in`, make sure that `flycheck-clojure-dep-version` is set to `"0.1.7"`.

**Comment by bobotu** [comment]
Thanks a lot

**Comment by pnf** [comment]
If you could test this out, prior to me closing the issue, that would be great.

**Comment by bobotu** [comment]
The new version works very well. This issue can be closed.

**Comment by pnf** [comment]
Great.  Thanks for reporting and testing this.
