### ISSUE TITLE
Dependency issue: CIDER warning: "version x.y.z does not match cider-nrepl's version"

### ISSUE THREAD

**Issue by mrroman** [clojure-emacs/squiggly-clojure#45]
When I install squiggly-clojure and flycheck-clojure in the Emacs, CIDER reports a warning:

"WARNING: CIDER's version (0.14.0) does not match cider-nrepl's version (nil). Things will break!”.

I've tried sending with CIDER a request by `(nrepl-send-sync-request '("op" "describe") (current-buffer))` and it doesn’t return `aux` dictionary.

I have Leiningen 2.7.1 and I use cider-stable. It has to be a dependency issue, because after removing squiggly dependencies, CIDER doesn't report error.

**Comment by expez** [comment]
> When I install squiggly-clojure and flycheck-clojure 

This is the same project.  Squiggly-clojure was the old name for the project.

How are you installing it?  What does your `profiles.clj` look like?  Is it broken in a `lein new test` project or just the project you're working on now?  If so, what's that's project `project.clj`

**Comment by mrroman** [comment]
Hi,

I don't have profiles.clj file. CIDER runs leiningen with this command:

/usr/local/bin/lein update-in :dependencies conj [acyclic/squiggly-clojure
"0.1.7"] -- update-in :dependencies conj [org.clojure/tools.nrepl "0.2.12"
:exclusions [org.clojure/clojure]] -- update-in :plugins conj
[refactor-nrepl "2.3.0-SNAPSHOT"] -- update-in :plugins conj
[cider/cider-nrepl "0.15.0-SNAPSHOT"] -- repl :headless

I've tried to isolate the issue and you can reproduce the issue with:

lein new some-project

My emacs settings are available here: https://github.com/mrroman/emacs.d.

PS. I don't see your comment added to github issue.

śr., 15 lut 2017 o 11:57 użytkownik Lars Andersen <notifications@github.com>
napisał:

**Comment by pnf** [comment]
Could you try removing the `(use-package flycheck-clojure ...)` and verifying that you can now `cider-jack-in` without error?

**Comment by mrroman** [comment]
Yes. I did that and the warning disappeared.

**Comment by pnf** [comment]
Odd. Could you try running, outside of emacs


/usr/local/bin/lein update-in :dependencies conj [acyclic/squiggly-clojure "0.1.7"] -- update-in :dependencies conj [org.clojure/tools.nrepl "0.2.12" :exclusions [org.clojure/clojure]] -- update-in :plugins conj [refactor-nrepl "2.3.0-SNAPSHOT"] -- update-in :plugins conj [cider/cider-nrepl "0.15.0-SNAPSHOT"] -- deps :tree

**Comment by mrroman** [comment]
Here is the output:

 [acyclic/squiggly-clojure "0.1.7"]
   [environ "1.0.0"]
   [jonase/eastwood "0.2.3" :exclusions [[org.clojure/clojure]]]
     [org.clojars.brenton/google-diff-match-patch "0.1"]
     [org.ow2.asm/asm-all "4.2"]
   [jonase/kibit "0.1.3"]
     [org.clojure/core.logic "0.8.11"]
     [org.clojure/tools.cli "0.3.5"]
   [org.clojure/core.typed "0.3.26" :exclusions [[org.clojure/clojure]]]
     [org.clojure/core.cache "0.6.4"]
       [org.clojure/data.priority-map "0.0.4"]
     [org.clojure/core.typed.rt "0.3.26"]
     [org.clojure/math.combinatorics "0.1.3" :exclusions [[org.clojure/clojure]]]
     [org.clojure/tools.analyzer.jvm "0.6.8"]
       [org.clojure/core.memoize "0.5.7"]
       [org.clojure/tools.analyzer "0.6.7"]
     [org.clojure/tools.namespace "0.3.0-alpha3"]
       [org.clojure/java.classpath "0.2.3"]
     [org.clojure/tools.reader "1.0.0-beta3"]
   [org.clojure/data.json "0.2.6"]
 [cider/cider-nrepl "0.15.0-20170207.071608-9"]
   [org.tcrawley/dynapath "0.2.5" :exclusions [[org.clojure/clojure]]]
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [com.stuartsierra/component "0.3.2"]
   [com.stuartsierra/dependency "0.2.0"]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
 [refactor-nrepl "2.3.0-20170210.162113-13"]

**Comment by mrroman** [comment]
The same without squiggly:

```
Possibly confusing dependencies found:
[org.clojure/tools.nrepl "0.2.12" :exclusions [org.clojure/clojure]]
 overrides
[org.clojure/tools.nrepl "0.2.12" :exclusions [org.clojure/clojure]]

Consider using these exclusions:


 [cider/cider-nrepl "0.15.0-20170207.071608-9"]
   [org.tcrawley/dynapath "0.2.5" :exclusions [[org.clojure/clojure]]]
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
 [refactor-nrepl "2.3.0-20170210.162113-13"]
```

**Comment by pnf** [comment]
I can replicate this now.  For some reason, the error does not occur when I specify dependencies in an equivalent `profiles.clj`, and since that's how I usually operate, I wouldn't normally encounter this.
 Since the version of `cider-nrepl` as reported by `lein deps` is in fact correct, I don't know that the cider warning is correct, and in fact I haven't seen any indication myself that "things will break".

Have you noticed any problems beyond the frightening warning from cider?

**Comment by mrroman** [comment]
I don't write those dependencies in the profiles.clj, because it causes longer lein startup. I didn't check that thorough the consequences. I'm trying to investigate now, why "describe" opcode doesn't return the :aux section :).

**Comment by pnf** [comment]
Put the dependencies in the `:repl` profile, and they won't affect lein startup for other uses.

**Comment by mrroman** [comment]
I wanted to use lein repl without loading cider-nrepl etc. :). I've isolated the problem. The issue is caused by `core.typed "0.3.26"`. When I downgraded it to `core.typed "0.3.7"`, the warning was gone.

**Comment by pnf** [comment]
Did you see anything broken other than the "things will break" message?

**Comment by pnf** [comment]
This seems to be related to AOT jars introduced with 0.3.26  @frenchy64 suggested adding `:classifier "slim"` after the `"0.3.32"` and indeed that "fixes" the problem (though I still don't know why).

**Comment by pnf** [comment]
Latest update to squiggly `0.1.9-SNAPSHOT` contains this and a few other changes.
