### ISSUE TITLE
(wrong-number-of-arguments (4 . 4) 0)

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/squiggly-clojure#46]
Hi,

first of all thanks for this checker. 

I just started a new project, using the [Luminus](http://www.luminusweb.net) template. After CIDER is up and running with `C-c M-j`, upon editing a `.clj` file I keep getting this error:
```
Debugger entered--Lisp error: (wrong-number-of-arguments (4 . 4) 0)
  #[1028 "\301\303\304\305\302\300$\"\207" [clojure-cider-eastwood #[128 "\301\302\300#\207" [[cl-struct-flycheck-syntax-check #<buffer home.clj> clojure-cider-eastwood "22" "/home/manuel/projects/mallory/src/clj/mallory/routes/"] apply flycheck-report-buffer-checker-status] 5 "\n\n(fn &rest ARGS)"] #[257 "\300\301\"\207" [format "(do (require 'squiggly-clojure.core) (squiggly-clojure.core/check-ew '%s))"] 4 "\n\n(fn NS)"] errored format "Form %s of checker %s failed: %s"] 11 "\n\n(fn BUFFER EX ROOTEX SESS)"]()
  #[257 "\307\310\"\307\311\"\307\312\"\307\313\"\307\314\"\307\315\"\307\316\"\317\300!\2038
```
Some extra info that might help to debug the issue:
- OS: Debian Jessie
- Emacs version: `GNU Emacs 26.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.14.5) of 2017-02-18` (commit `861ff2b`)
- CIDER version: `CIDER 0.15.0snapshot (package: 20170129.1941)`
- Flycheck version: `Flycheck version: 31snapshot (package: 20170212.1015)`
- `flycheck-clojure-dep-version`: `0.1.7`

**Comment by pnf** [comment]
Could you show me the result of running the `(do (require ... )` form straight from the REPL?

**Comment by manuel-uberti** [comment]
This is what I get:
```
user> (do (require 'squiggly-clojure.core) (squiggly-clojure.core/check-ew '%s))

;; => "[]"
```

**Comment by pnf** [comment]
Well, that's what we expect, so the problem has to be in the transmission of this boring result back to emacs. Out of curiosity, did you get a "things will break" warning when cider started? 
What I'm beginning to suspect is a conflict between the dependencies of the latest cider-nrepl snapshot and those of core.async.

**Comment by manuel-uberti** [comment]
No, no issue with CIDER. Neither in the `*Messages*` buffer, nor in the REPL.

**Comment by pnf** [comment]
Ok. I won't have access to a real computer for a few hours, but in the mean time, a few more questions.
1. Definitely no message when cider starts about a mismatched cider-nrepl version? I ask because others have reported this.
2. Are you setting the dependencies in a profile or via jack-in? Whichever it is, can you try the other one?

**Comment by anujsrc** [comment]
@pnf - I am also facing the same issue. If we add the squiggly dependency in ~/.lein/profiles.clj as mentioned in https://github.com/clojure-emacs/squiggly-clojure/issues/29 and https://github.com/clojure-emacs/squiggly-clojure/issues/39, the checker error goes way but I start getting the CIDER warning as mentioned here- https://github.com/clojure-emacs/cider/issues/1728 - It does say things may break as you pointed out.

**Comment by manuel-uberti** [comment]
@pnf 

1. Yes, no message at all about the mismatched `cider-nrepl` version
2. I am setting the dependencies via jack-in. If I try the other way, I get the same behaviour as @anujsrc.

**Comment by pnf** [comment]
I have been completely unsuccessful determining how cider determines what version of `cider-nrepl` is being used.  (@bbatsov can you give me some pointers?)  In any case, we clearly are using the correct one, as confirmed both by the `lein deps :tree` output and looking at `cider.nrepl.version/version` directly from the REPL.
@manuel-uberti, @anujsrc - Other than the CIDER warning, do you see anything - regular CIDER or squiggly functionality - actually breaking?  My experience is that the `wrong-number-of-arguments` error from squiggly and the `things may break` warning from cider are orthogonal: i.e. squiggly breaks only when I didn't get the warning.
One slight improvement I can make is to push the `org.clojure/clojure` dependency up to "1.8.0".  When I do that, then (with a fresh `lein new luminous` project): (1) The behavior with injected dependencies from`cider-jack-in` and with explicit dependencies in the `:repl` profile is identical; both result in the breakage warning, but no evident breakage. (2) A whole bunch of  `lein with-profile repl deps :tree` inconsistency go away; I'm left with a few relating only to luminous, and an internal inconsistency within the `core.typed` dependency tree on `tools.reader`.  By adding `toos.reader` to the exclusions for `acyclic/squiggly-clojure`, we can remove that last inconsistency warning, but it does not, as I'd hoped, somehow cause the "things may break" warning to go away.
Later today, I'll push a squiggly "0.1.8" jar that depends on `clojure` "1.8.0" and modify the `.el.` to inject that dependency, along with the reader exclusion.   There may be up to a day before the new elisp hits melpa, so there may be a period where you have to modify `flycheck-clojure-dep-version` manually.

**Comment by pnf** [comment]
Updated `flycheck-clojure.el` is on github ready for pick-up by melpa; the new jar, version "0.1.8" is up on clojars.  Following @mrroman's discovery that the mismatched version warning only occurs with versions of `core.typed` 0.3.26 and later, I reverted the squiggly dependency to `0.3.25`.  I also brought this up on the core.typed google group, as the cider error can be reproduced without involving squiggly at all.
At this point, I believe that the README, the sample project, the clojar and the .el are all in sync, and you should no longer see either things breaking or a warning that they will.  (Well, things will break eventually, but hopefully not in the way we've been discussing.)

**Comment by pnf** [comment]
Per #45, the version mismatch error has something to do with AOT jars from `core.typed`, by explicitly depending on `"0.3.32" :classifier "slim"`.  So, yet another version tick today.  Now to squiggly `0.1.9-SNAPSHOT`.  (So I can rashly push out further updates without having to change the version as often.)

**Comment by anujsrc** [comment]
Thanks @pnf - I will pull the SNAPSHOT tomorrow and give it a try.

**Comment by manuel-uberti** [comment]
Thanks for your effort @pnf, but I am still getting the same error message. I upgraded `flycheck-clojure`, jacked-in with `C-c M-j` and at every edit in a `.clj` file I get the message.

**Comment by pnf** [comment]
Are you using the latest .el, which injects 0.1.9-SNAPSHOT?
If so, there's something in your environment that that I don't understand. I am testing on a new luminous project, with no profile set.

**Comment by manuel-uberti** [comment]
Yes, latest version with 0.1.9-SNAPSHOT. I'll try again on a new luminus project later and report back.

**Comment by pnf** [comment]
You see exactly this?
```
Starting nREPL server via /home/pnf/bin/lein update-in :dependencies conj \[acyclic/squiggly-clojure\ \"
0.1.9-SNAPSHOT\"\ \:exclusions\ \[org.clojure/tools.reader\]\] -- update-in :dependencies conj \[org.clo
jure/tools.nrepl\ \"0.2.12\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refac
tor-nrepl\ \"2.3.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.15.0-SNAPSHOT\"\] --
 repl :headless...
```

**Comment by manuel-uberti** [comment]
No, actually I got this:
```
Starting nREPL server via /home/manuel/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refactor-nrepl\ \"2.3.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.15.0-SNAPSHOT\"\] -- repl :headless...
```

**Comment by pnf** [comment]
This doesn't mention squiggly at all. Are you sure you have the latest .el from github and have executed flycheck-clojure-setup?

**Comment by manuel-uberti** [comment]
Yes.
```
flycheck-clojure-dep-version is a variable defined in ‘flycheck-clojure.el’.
Its value is "0.1.9-SNAPSHOT"
```
And in `*Messages*`:
```
error in process filter: Wrong number of arguments: (4 . 4), 0 [2 times]
Error from syntax checker clojure-cider-eastwood: Done with no errors
```

**Comment by pnf** [comment]
That variable is defined when the .el is eval'd. It's the -setup function that adds it to the cider injection list.  If you don't see the dependency in the lein parameters, then either -setup wasn't run, or you have some other problem. In either case, the squiggly jars won't be on your class path, so it would be surprising if anything worked.

**Comment by manuel-uberti** [comment]
This is weird, because if I completely disable `flycheck-clojure` I'm not getting the error. I'll check again my setup.

**Comment by pnf** [comment]
It sort of makes sense. If we're somehow evaluating flycheck-clojure functions without having the classes available, something terrible will happen.

**Comment by manuel-uberti** [comment]
This is my config:
```
(use-package flycheck-clojure           ; Setup Flycheck for Clojure
  :ensure t
  :defer t
  :after flycheck
  :config (flycheck-clojure-setup))
```
I'll try running `flycheck-clojure-setup` withouth waiting for Flycheck to be loaded and see if it makes any difference.

**Comment by manuel-uberti** [comment]
Nothing changed. My setup now:
```
(eval-after-load 'flycheck '(flycheck-clojure-setup))
```
Error message:
```
Starting nREPL server via /home/manuel/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refactor-nrepl\ \"2.3.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.15.0-SNAPSHOT\"\] -- repl :headless...
```

**Comment by pnf** [comment]
The injection occurs at
https://github.com/clojure-emacs/squiggly-clojure/blob/master/elisp/flycheck-clojure/flycheck-clojure.el#L196
You can examine `cider-jack-in-dependencies` directly.

**Comment by manuel-uberti** [comment]
I eval'd `flycheck-clojure-setup` via `M-x`, now I get the injection.
This is what Flycheck is reporting in a `.clj` buffer:
```
core.typed:There was previously an unrecoverable internal error while loading core.typed. Please restart your process. (clojure-cider-typed)
```

**Comment by pnf** [comment]
Officially, you're on your own for issues with individual linters.
However, I suspect you'll want to turn off `core.typed` here, unless you're actually using it in the project. 
You should probably test out a few bona-fide Eastwood and Kibit solecisms to make sure they're being highlighted.

**Comment by manuel-uberti** [comment]
Ok great. Let's consider this closed then.

Thank you for the patience and the support.

**Comment by pnf** [comment]
You're very welcome.

**Comment by manuel-uberti** [comment]
[This](https://github.com/clojure-emacs/squiggly-clojure/issues/47#issuecomment-288486651) fixed it.
