### ISSUE TITLE
Setup successful?

### ISSUE THREAD

**Issue by fleimgruber** [clojure-emacs/squiggly-clojure#52]
Given the following `project.clj`
``` clojure
(defproject captcha "0.1.0-SNAPSHOT"
  ...
  :dependencies [[org.clojure/clojure "1.8.0"]]
  :profiles {:dev {:plugins [[cider/cider-nrepl "0.14.0"]]
                   :dependencies [[org.clojure/tools.nrepl "0.2.13"]
                                  [acyclic/squiggly-clojure "0.1.8" :exclusions [org.clojure/tools.reader]]]}})
```
and doing a
```
lein with-profile +dev repl
```
followed by `cider-connect` to this repl, I get a working cider setup.  I followed the instructions for Emacs side config of `flycheck-clojure`.  In the connected source buffer, a `flycheck-verify-setup` leads to
```
Syntax checkers for buffer core.clj in clojure-mode:

  clojure-cider-eastwood
    - may enable: yes
    - predicate:  t

  clojure-cider-kibit
    - may enable: yes
    - predicate:  t

  clojure-cider-typed
    - may enable: yes
    - predicate:  t

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled checkers.
```
and no flycheck errors are displayed although there is the line `(inc "foo")` in the clj source buffer.

Am I mis(u)sing something?

**Comment by biancazzurri** [comment]
Not working for me also, I get error about max-specpdl-size (exceeded depth)

**Comment by pnf** [comment]
Have you followed the debugging suggestions in the `README`?

**Comment by pnf** [comment]
Actually... Have you tried starting by `cider-jack-in`.  I realize that the shields.io badge is showing the wrong version of `squiggly-clojure`, which ought to be `0.1.9-SNAPSHOT`.

**Comment by biancazzurri** [comment]
Been trying to make it work for 3 days, I tried them all, also asked my colleagues to try to use it. Not working :(

**Comment by fleimgruber** [comment]
After digging through #46 and #47, I found https://github.com/clojure-emacs/squiggly-clojure/issues/47#issuecomment-288486651, so I got it working by

```
(eval-after-load 'cider '(flycheck-clojure-setup))
```

and `cider-jack-in` on sample-project/src/sample_project/core.clj
