### ISSUE TITLE
Do I need to have this package loaded after clojure-mode and cider?

### ISSUE THREAD

**Issue by re-mx** [clojure-emacs/squiggly-clojure#55]
Hello:

Re: purcell/emacs.d#502

Do I really need to load flycheck-clojure after cider and clojure-mode?

Thanks.

**Comment by scottdw** [comment]
Not necessarily, `flycheck-clojure-setup` depends on the cider variable `cider-jack-in-dependencies` being bound to ensure that the squiggly jar is injected on `cider-jack-in`. So you could load flycheck-clojure before cider and wait to call `flycheck-clojure-setup` on cider load.

Or if you can ensure that the squiggly jar is available by some other means (dev profiles in lein/boot/deps etc.) then you don't need to rely on `cider-jack-in-dependencies` and `flycheck-clojure-setup` can be called before cider is loaded.

**Comment by re-mx** [comment]
Thanks
