### ISSUE TITLE
(wrong-number-of-arguments (4 . 4) 0)

### ISSUE THREAD

**Issue by DeadEarnest** [clojure-emacs/squiggly-clojure#57]
I looked at the previous issues with the same error, but was unable to find a solution.
I use cider-jack-in and get the following error while editing a Clojure source file:

Debugger entered--Lisp error: (wrong-number-of-arguments (4 . 4) 0)
  #[1028 "\301\303\304\305\302\300$\"\207" [clojure-cider-eastwood #[128 "\301\302\300#\207" [[cl-struct-flycheck-syntax-check #<buffer core.clj> clojure-cider-eastwood "7" "/mnt/sda2/work/code/clojure_noob/src/clojure_noob/"] apply flycheck-report-buffer-checker-status] 5 "\n\n(fn &rest ARGS)"] #[257 "\300\301\"\207" [format "(do (require 'squiggly-clojure.core) (squiggly-clojure.core/check-ew '%s))"] 4 "\n\n(fn NS)"] errored format "Form %s of checker %s failed: %s"] 11 "\n\n(fn BUFFER EX ROOTEX SESS)"]()
  #[257 "\310\311\"\310\312\"\310\313\"\310\314\"\310\315\"\310\316\"\310\317\"\310\320\"\310	\321\"\322\300!\203A

Tried this with [org.clojure/clojure "1.8.0"], [org.clojure/clojure "1.9.0"], [org.clojure/clojure "1.10.0"]. No warnings when I start the REPL. The startup message:

[nREPL] Starting server via /home/qwe/.local/bin/lein update-in :dependencies conj \[acyclic/squiggly-clojure\ \"0.1.9-SNAPSHOT\"\ \:exclusions\ \[org.clojure/tools.reader\]\] -- update-in :dependencies conj \[nrepl\ \"0.6.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.22.0-beta4\"\] -- repl :headless :host localhost...

**Comment by pnf** [comment]
First, could you try disabling the`clojure-cider-typed` checker?  There have been problems where a checker throws an exception and produces output that cider can't parse, and `typed` is the most fiddly of the checkers.
Also, if you're feeling generous, could you test out squiggly clojure on the sample-project in this repo? 
Finally, what `Package-Version' do you see in the `flycheck-clojure.el` headers?

**Comment by DeadEarnest** [comment]
Tested out `sample-project`, it worked OK. Then compared it's `project.clj` with mine `project.clj`, mine was lacking 

> :dependencies [[org.clojure/core.typed "0.5.3"  :classifier "slim"]]

After I added this dependency, the problem was solved. Thanks for helping.

**Comment by pnf** [comment]
Excellent.
